"""change chars to pilots

Revision ID: 0004
Revises: 0003
Create Date: 2025-09-14 17:33:44.414311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starshippilotlink', sa.Column('pilot_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('starshippilotlink_character_id_fkey'), 'starshippilotlink', type_='foreignkey')
    op.create_foreign_key(None, 'starshippilotlink', 'character', ['pilot_id'], ['id'])
    op.drop_column('starshippilotlink', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starshippilotlink', sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'starshippilotlink', type_='foreignkey')
    op.create_foreign_key(op.f('starshippilotlink_character_id_fkey'), 'starshippilotlink', 'character', ['character_id'], ['id'])
    op.drop_column('starshippilotlink', 'pilot_id')
    # ### end Alembic commands ###
