"""add swapi url

Revision ID: 0005
Revises: 0004
Create Date: 2025-09-14 23:09:39.049703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('swapi_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('film', sa.Column('swapi_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('starship', sa.Column('swapi_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starship', 'swapi_url')
    op.drop_column('film', 'swapi_url')
    op.drop_column('character', 'swapi_url')
    # ### end Alembic commands ###
